services:
  app:
    image: hello-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: hello-front-dev # This will name the container hello-front-dev
    environment: # hot reloading: https://stackoverflow.com/a/44643246
      - CHOKIDAR_USEPOLLING=true # high CPU usage, a potential alternative: https://stackoverflow.com/a/67209565