version: '3.8'

services:
  backend:
    image: phonebook-backend-development
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3000"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db
  frontend:
    image: phonebook-frontend-development
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment:
      # - WDS_SOCKET_PORT=0 # https://github.com/facebook/create-react-app/issues/11897#issuecomment-1007206461
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy